name: zz/workflow-demo
on:
  workflow_dispatch:
    inputs:
      greeting:
        description: "Greeting word"
        required: true
        default: "Hello"
      name:
        description: "Name to greet"
        required: false
        default: "World"
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.inputs.greeting }}, ${{ github.event.inputs.name }}!"
